import { gerarProtocolo } from '@/lib/constants'
import { createDefaultAdminAccessMatrix } from '@/lib/admin-access'
import { hashPassword } from '@/lib/server/security'
import type {
  AppDatabase,
  AppSettingsRecord,
  AppUserRecord,
  DepartmentRecord,
  ManifestationRecord,
  ResponseTemplateRecord,
  SatisfactionSurveyRecord,
} from '@/lib/server/schema'

function isoDaysFromNow(days: number) {
  const date = new Date()
  date.setDate(date.getDate() + days)
  return date.toISOString()
}

function buildSettings(): AppSettingsRecord {
  return {
    empresa: {
      nomeEmpresa: 'ArtGlass Esquadrias',
      cnpj: '12.345.678/0001-90',
      emailOuvidoria: 'ouvidoria@artglass.com.br',
      telefone: '(11) 3456-7890',
      endereco: 'Av. Industrial, 1000 - Sao Paulo, SP',
      portalTitulo: 'Ouvidoria ArtGlass',
      portalMensagemBoasVindas:
        'Bem-vindo ao canal seguro, confidencial e imparcial da Ouvidoria ArtGlass. Registre aqui sugestoes, elogios, reclamacoes, consultas e denuncias.',
      permitirAnonimo: true,
      permitirAnexos: true,
      canalDenunciasAtivo: true,
      smtpHost: 'smtp.artglass.com.br',
      smtpPort: '587',
      smtpUser: 'ouvidoria@artglass.com.br',
      smtpPasswordMasked: '********',
      smtpTls: true,
    },
    notificacoes: {
      novaManifestacao: true,
      novaDenuncia: true,
      manifestacaoAtribuida: true,
      respostaManifestante: true,
      resumoDiario: false,
      confirmacaoRecebimento: true,
      atualizacaoStatus: true,
      respostaOuvidoria: true,
      pesquisaSatisfacao: true,
    },
    sla: {
      reclamacao: { respostaInicialHoras: 24, resolucaoDias: 5 },
      sugestao: { respostaInicialHoras: 48, resolucaoDias: 10 },
      denuncia: { respostaInicialHoras: 12, analiseInicialDias: 3 },
      proximidadePercentual: 25,
      alertaVencido: true,
      escalacaoAutomatica: true,
    },
    acessos: createDefaultAdminAccessMatrix(),
  }
}

function buildDepartments(now: string): DepartmentRecord[] {
  return [
    {
      id: 'dept-comercial',
      nome: 'Comercial',
      responsavel: 'Roberto Lima',
      email: 'comercial@artglass.com.br',
      ativo: true,
      criadoEm: now,
      atualizadoEm: now,
    },
    {
      id: 'dept-producao',
      nome: 'Producao',
      responsavel: 'Fernanda Souza',
      email: 'producao@artglass.com.br',
      ativo: true,
      criadoEm: now,
      atualizadoEm: now,
    },
    {
      id: 'dept-logistica',
      nome: 'Logistica',
      responsavel: 'Andre Martins',
      email: 'logistica@artglass.com.br',
      ativo: true,
      criadoEm: now,
      atualizadoEm: now,
    },
    {
      id: 'dept-rh',
      nome: 'Recursos Humanos',
      responsavel: 'Luciana Alves',
      email: 'rh@artglass.com.br',
      ativo: true,
      criadoEm: now,
      atualizadoEm: now,
    },
    {
      id: 'dept-financeiro',
      nome: 'Financeiro',
      responsavel: 'Ricardo Gomes',
      email: 'financeiro@artglass.com.br',
      ativo: true,
      criadoEm: now,
      atualizadoEm: now,
    },
    {
      id: 'dept-ti',
      nome: 'TI',
      responsavel: 'Bruno Pereira',
      email: 'ti@artglass.com.br',
      ativo: true,
      criadoEm: now,
      atualizadoEm: now,
    },
  ]
}

function buildUsers(now: string): AppUserRecord[] {
  const senhaHash = hashPassword('ArtGlass@123')

  return [
    {
      id: 'user-admin-geral',
      nome: 'Administrador Geral',
      email: 'admin@artglass.com.br',
      perfil: 'admin',
      senhaHash,
      ativo: true,
      criadoEm: now,
      atualizadoEm: now,
    },
    {
      id: 'user-maria-ouvidoria',
      nome: 'Maria Silva',
      email: 'maria.silva@artglass.com.br',
      perfil: 'ouvidoria',
      senhaHash,
      ativo: true,
      criadoEm: now,
      atualizadoEm: now,
    },
    {
      id: 'user-ana-ouvidoria',
      nome: 'Ana Costa',
      email: 'ana.costa@artglass.com.br',
      perfil: 'ouvidoria',
      senhaHash,
      ativo: true,
      criadoEm: now,
      atualizadoEm: now,
    },
    {
      id: 'user-carlos-area',
      nome: 'Carlos Santos',
      email: 'carlos.santos@artglass.com.br',
      perfil: 'area_tecnica',
      areaId: 'dept-comercial',
      senhaHash,
      ativo: true,
      criadoEm: now,
      atualizadoEm: now,
    },
    {
      id: 'user-maria-area',
      nome: 'Maria Oliveira',
      email: 'maria.oliveira@artglass.com.br',
      perfil: 'area_tecnica',
      areaId: 'dept-producao',
      senhaHash,
      ativo: true,
      criadoEm: now,
      atualizadoEm: now,
    },
    {
      id: 'user-andre-logistica',
      nome: 'Andre Martins',
      email: 'andre.martins@artglass.com.br',
      perfil: 'area_tecnica',
      areaId: 'dept-logistica',
      senhaHash,
      ativo: true,
      criadoEm: now,
      atualizadoEm: now,
    },
    {
      id: 'user-ricardo-financeiro',
      nome: 'Ricardo Gomes',
      email: 'ricardo.gomes@artglass.com.br',
      perfil: 'area_tecnica',
      areaId: 'dept-financeiro',
      senhaHash,
      ativo: true,
      criadoEm: now,
      atualizadoEm: now,
    },
    {
      id: 'user-bruno-ti',
      nome: 'Bruno Pereira',
      email: 'bruno.pereira@artglass.com.br',
      perfil: 'area_tecnica',
      areaId: 'dept-ti',
      senhaHash,
      ativo: true,
      criadoEm: now,
      atualizadoEm: now,
    },
    {
      id: 'user-joao-comite',
      nome: 'Joao Ferreira',
      email: 'joao.ferreira@artglass.com.br',
      perfil: 'comite_etica',
      senhaHash,
      ativo: true,
      criadoEm: now,
      atualizadoEm: now,
    },
    {
      id: 'user-paula-comite',
      nome: 'Paula Costa',
      email: 'paula.costa@artglass.com.br',
      perfil: 'comite_etica',
      senhaHash,
      ativo: true,
      criadoEm: now,
      atualizadoEm: now,
    },
    {
      id: 'user-roberto-diretoria',
      nome: 'Roberto Lima',
      email: 'roberto.lima@artglass.com.br',
      perfil: 'diretoria',
      senhaHash,
      ativo: true,
      criadoEm: now,
      atualizadoEm: now,
    },
    {
      id: 'user-luciana-rh',
      nome: 'Luciana Alves',
      email: 'luciana.alves@artglass.com.br',
      perfil: 'rh',
      areaId: 'dept-rh',
      senhaHash,
      ativo: true,
      criadoEm: now,
      atualizadoEm: now,
    },
  ]
}

function buildTemplates(now: string): ResponseTemplateRecord[] {
  return [
    {
      id: 'template-confirmacao',
      titulo: 'Confirmacao de recebimento',
      descricao: 'Mensagem enviada automaticamente ao registrar uma manifestacao.',
      assunto: 'Confirmacao de recebimento - Protocolo {PROTOCOLO}',
      corpo:
        'Prezado(a),\n\nConfirmamos o recebimento da sua manifestacao registrada sob o protocolo {PROTOCOLO}.\n\nNossa equipe iniciara a analise e mantera voce informado(a) dentro dos prazos da Ouvidoria.\n\nAtenciosamente,\nOuvidoria ArtGlass',
      tipo: 'inicial',
      envioAutomatico: true,
      categoria: 'automatico',
      criadoEm: now,
      atualizadoEm: now,
    },
    {
      id: 'template-esclarecimentos',
      titulo: 'Solicitacao de esclarecimentos',
      descricao: 'Solicita mais detalhes ao manifestante.',
      assunto: 'Necessidade de informacoes adicionais - {PROTOCOLO}',
      corpo:
        'Para seguirmos com a analise da manifestacao {PROTOCOLO}, precisamos de informacoes complementares. Responda este e-mail com os detalhes que considerar relevantes.',
      tipo: 'esclarecimento',
      envioAutomatico: false,
      categoria: 'manual',
      criadoEm: now,
      atualizadoEm: now,
    },
    {
      id: 'template-reclamacao-procedente',
      titulo: 'Resposta de reclamacao procedente',
      descricao: 'Modelo de resposta conclusiva para reclamacoes procedentes.',
      assunto: 'Retorno da Ouvidoria - {PROTOCOLO}',
      corpo:
        'Concluimos a analise da manifestacao {PROTOCOLO}. As areas responsaveis adotaram as providencias cabiveis e seguimos acompanhando a estabilidade da solucao apresentada.',
      tipo: 'conclusiva',
      envioAutomatico: false,
      categoria: 'manual',
      criadoEm: now,
      atualizadoEm: now,
    },
    {
      id: 'template-agradecimento-sugestao',
      titulo: 'Agradecimento por sugestao',
      descricao: 'Agradece a colaboracao do manifestante.',
      assunto: 'Agradecimento pela sua contribuicao - {PROTOCOLO}',
      corpo:
        'Agradecemos pela sugestao registrada no protocolo {PROTOCOLO}. A contribuicao foi encaminhada para avaliacao tecnica e podera apoiar melhorias em nossos processos.',
      tipo: 'conclusiva',
      envioAutomatico: false,
      categoria: 'manual',
      criadoEm: now,
      atualizadoEm: now,
    },
    {
      id: 'template-pesquisa-satisfacao',
      titulo: 'Pesquisa de satisfacao',
      descricao: 'Convida o manifestante a avaliar o atendimento.',
      assunto: 'Como foi sua experiencia com a Ouvidoria?',
      corpo:
        'Sua manifestacao {PROTOCOLO} foi concluida. Gostariamos de ouvir sua opiniao sobre o atendimento prestado pela Ouvidoria.',
      tipo: 'conclusiva',
      envioAutomatico: true,
      categoria: 'automatico',
      criadoEm: now,
      atualizadoEm: now,
    },
  ]
}

function buildManifestations(now: string): ManifestationRecord[] {
  return [
    {
      id: 'man-1',
      protocolo: gerarProtocolo(1),
      natureza: 'reclamacao',
      naturezaOriginal: 'reclamacao',
      assunto: 'atendimento',
      complexidade: 'baixa',
      prioridade: 'alta',
      status: 'encaminhada_area',
      statusPublico: 'encaminhada_tratativa',
      laneAtual: 'area_responsavel',
      canalOrigem: 'site',
      titulo: 'Atraso no retorno sobre pedido de esquadrias',
      descricao:
        'O cliente relata atraso no retorno da equipe comercial e deseja uma posicao clara sobre o prazo de entrega.',
      dataOcorrido: isoDaysFromNow(-4),
      localOcorrido: 'Sao Paulo - SP',
      pessoasEnvolvidas: 'Equipe comercial',
      tentativaAnterior: 'sim',
      descricaoTentativa: 'Contato realizado pelo SAC sem solucao definitiva.',
      situacaoEmAndamento: 'sim',
      riscoImediato: 'nao',
      manifestante: {
        tipoIdentificacao: 'identificada',
        nome: 'Joao Carlos Ferreira',
        email: 'joao.ferreira@email.com',
        telefone: '(11) 99999-8888',
        relacaoArtGlass: 'cliente',
        desejaRetorno: 'email',
        melhorHorario: 'Tarde',
        consentimentoLgpd: true,
        declaracaoVerdade: true,
      },
      areaResponsavelId: 'dept-comercial',
      responsavelAtualId: 'user-carlos-area',
      prazoRespostaInicial: isoDaysFromNow(2),
      prazoRespostaFinal: isoDaysFromNow(11),
      dataRespostaInicial: isoDaysFromNow(-1),
      prorrogada: false,
      anexos: [],
      comunicacoes: [
        {
          id: 'com-1',
          tipo: 'inicial',
          assunto: `Confirmacao de recebimento - Protocolo ${gerarProtocolo(1)}`,
          corpo: 'Sua manifestacao foi recebida e esta em tratativa com a area responsavel.',
          de: 'Ouvidoria ArtGlass',
          para: 'joao.ferreira@email.com',
          status: 'enviada',
          canal: 'email',
          enviadaEm: isoDaysFromNow(-2),
          criadaEm: isoDaysFromNow(-2),
        },
      ],
      comentarios: [],
      timeline: [
        {
          id: 'time-1',
          data: isoDaysFromNow(-2),
          usuario: 'Sistema',
          acao: 'Manifestacao registrada',
          descricao: `Protocolo ${gerarProtocolo(1)} gerado automaticamente.`,
          visibilidade: 'publica',
        },
        {
          id: 'time-2',
          data: isoDaysFromNow(-2),
          usuario: 'Sistema',
          acao: 'Confirmacao enviada',
          descricao: 'E-mail de confirmacao enviado ao manifestante.',
          visibilidade: 'publica',
        },
        {
          id: 'time-3',
          data: isoDaysFromNow(-1),
          usuario: 'Maria Silva',
          acao: 'Encaminhamento para area responsavel',
          descricao: 'Caso encaminhado ao Comercial com termo de confidencialidade.',
          visibilidade: 'interna',
        },
      ],
      criadoEm: isoDaysFromNow(-2),
      atualizadoEm: isoDaysFromNow(-1),
    },
    {
      id: 'man-2',
      protocolo: gerarProtocolo(2),
      natureza: 'denuncia',
      naturezaOriginal: 'denuncia',
      assunto: 'assedio_moral',
      complexidade: 'alta',
      prioridade: 'critica',
      status: 'em_analise_comite',
      statusPublico: 'em_apuracao',
      laneAtual: 'comite_etica',
      canalOrigem: 'site',
      titulo: 'Relato de assedio moral por lideranca imediata',
      descricao:
        'Denuncia sigilosa envolvendo relatos recorrentes de assedio moral praticado por lideranca da area operacional.',
      dataOcorrido: isoDaysFromNow(-6),
      localOcorrido: 'Unidade fabril',
      pessoasEnvolvidas: 'Gestor imediato e equipe operacional',
      tentativaAnterior: 'nao',
      situacaoEmAndamento: 'sim',
      riscoImediato: 'sim',
      manifestante: {
        tipoIdentificacao: 'sigilosa',
        nome: 'Manifestante Sigiloso',
        email: 'sigiloso@provedor.com',
        relacaoArtGlass: 'colaborador',
        desejaRetorno: 'email',
        consentimentoLgpd: true,
        declaracaoVerdade: true,
      },
      responsavelAtualId: 'user-joao-comite',
      prazoRespostaInicial: isoDaysFromNow(1),
      prazoRespostaFinal: isoDaysFromNow(8),
      dataRespostaInicial: isoDaysFromNow(-4),
      prorrogada: false,
      anexos: [],
      comunicacoes: [
        {
          id: 'com-2',
          tipo: 'inicial',
          assunto: `Confirmacao de recebimento - Protocolo ${gerarProtocolo(2)}`,
          corpo: 'Sua denuncia foi recebida e sera tratada com confidencialidade.',
          de: 'Ouvidoria ArtGlass',
          para: 'sigiloso@provedor.com',
          status: 'enviada',
          canal: 'email',
          enviadaEm: isoDaysFromNow(-5),
          criadaEm: isoDaysFromNow(-5),
        },
      ],
      comentarios: [],
      timeline: [
        {
          id: 'time-4',
          data: isoDaysFromNow(-5),
          usuario: 'Sistema',
          acao: 'Denuncia registrada',
          descricao: 'Manifestacao recebida e encaminhada para analise de pertinencia.',
          visibilidade: 'publica',
        },
        {
          id: 'time-5',
          data: isoDaysFromNow(-4),
          usuario: 'Maria Silva',
          acao: 'Pertinencia confirmada',
          descricao: 'Caso considerado pertinente e submetido ao Comitê de Ética.',
          visibilidade: 'interna',
        },
      ],
      criadoEm: isoDaysFromNow(-5),
      atualizadoEm: isoDaysFromNow(-4),
    },
    {
      id: 'man-3',
      protocolo: gerarProtocolo(3),
      natureza: 'sugestao',
      naturezaOriginal: 'sugestao',
      assunto: 'processo_interno',
      complexidade: 'baixa',
      prioridade: 'baixa',
      status: 'concluida',
      statusPublico: 'concluida',
      laneAtual: 'ouvidoria',
      canalOrigem: 'site',
      titulo: 'Sugestao para melhorar devolutiva de status',
      descricao: 'Cliente sugere envio automatico de etapas do pedido para reduzir contatos repetidos.',
      tentativaAnterior: 'nao_aplica',
      situacaoEmAndamento: 'nao',
      riscoImediato: 'nao',
      manifestante: {
        tipoIdentificacao: 'identificada',
        nome: 'Lara Martins',
        email: 'lara@email.com',
        relacaoArtGlass: 'cliente',
        desejaRetorno: 'email',
        consentimentoLgpd: true,
        declaracaoVerdade: true,
      },
      areaResponsavelId: 'dept-ti',
      responsavelAtualId: 'user-ana-ouvidoria',
      prazoRespostaInicial: isoDaysFromNow(-18),
      prazoRespostaFinal: isoDaysFromNow(-5),
      dataRespostaInicial: isoDaysFromNow(-18),
      dataRespostaFinal: isoDaysFromNow(-5),
      prorrogada: false,
      anexos: [],
      comunicacoes: [
        {
          id: 'com-3',
          tipo: 'conclusiva',
          assunto: `Retorno da Ouvidoria - ${gerarProtocolo(3)}`,
          corpo: 'A sugestao foi encaminhada para avaliacao do time de TI e integrara a fila de melhorias do portal.',
          de: 'Ouvidoria ArtGlass',
          para: 'lara@email.com',
          status: 'enviada',
          canal: 'email',
          enviadaEm: isoDaysFromNow(-5),
          criadaEm: isoDaysFromNow(-5),
        },
      ],
      comentarios: [],
      timeline: [
        {
          id: 'time-6',
          data: isoDaysFromNow(-20),
          usuario: 'Sistema',
          acao: 'Manifestacao registrada',
          descricao: 'Sugestao recebida com protocolo para acompanhamento.',
          visibilidade: 'publica',
        },
        {
          id: 'time-7',
          data: isoDaysFromNow(-5),
          usuario: 'Ana Costa',
          acao: 'Resposta conclusiva enviada',
          descricao: 'Manifestante informado sobre avaliacao e registro da melhoria.',
          visibilidade: 'publica',
        },
      ],
      criadoEm: isoDaysFromNow(-20),
      atualizadoEm: isoDaysFromNow(-5),
      concluidoEm: isoDaysFromNow(-5),
    },
    {
      id: 'man-4',
      protocolo: gerarProtocolo(4),
      natureza: 'elogio',
      naturezaOriginal: 'elogio',
      assunto: 'atendimento',
      complexidade: 'baixa',
      prioridade: 'baixa',
      status: 'concluida',
      statusPublico: 'concluida',
      laneAtual: 'rh',
      canalOrigem: 'site',
      titulo: 'Elogio ao atendimento da loja',
      descricao: 'Manifestante registrou elogio ao atendimento prestado por colaboradora da recepcao.',
      tentativaAnterior: 'nao_aplica',
      situacaoEmAndamento: 'nao',
      riscoImediato: 'nao',
      manifestante: {
        tipoIdentificacao: 'identificada',
        nome: 'Paulo Henrique',
        email: 'paulo@email.com',
        relacaoArtGlass: 'cliente',
        desejaRetorno: 'email',
        consentimentoLgpd: true,
        declaracaoVerdade: true,
      },
      areaResponsavelId: 'dept-rh',
      responsavelAtualId: 'user-luciana-rh',
      prazoRespostaInicial: isoDaysFromNow(-10),
      prazoRespostaFinal: isoDaysFromNow(-2),
      dataRespostaInicial: isoDaysFromNow(-9),
      dataRespostaFinal: isoDaysFromNow(-2),
      prorrogada: false,
      anexos: [],
      comunicacoes: [],
      comentarios: [],
      timeline: [
        {
          id: 'time-8',
          data: isoDaysFromNow(-12),
          usuario: 'Sistema',
          acao: 'Manifestacao registrada',
          descricao: 'Elogio recebido e encaminhado ao RH.',
          visibilidade: 'publica',
        },
      ],
      criadoEm: isoDaysFromNow(-12),
      atualizadoEm: isoDaysFromNow(-2),
      concluidoEm: isoDaysFromNow(-2),
    },
    {
      id: 'man-5',
      protocolo: gerarProtocolo(5),
      natureza: 'solicitacao_complexa',
      naturezaOriginal: 'solicitacao_complexa',
      assunto: 'qualidade_produto',
      complexidade: 'alta',
      prioridade: 'media',
      status: 'aguardando_minuta',
      statusPublico: 'encaminhada_tratativa',
      laneAtual: 'area_responsavel',
      canalOrigem: 'email',
      titulo: 'Solicitacao de analise tecnica sobre esquadrias instaladas',
      descricao: 'Cliente solicita orientacao especializada sobre desempenho de esquadrias instaladas.',
      tentativaAnterior: 'sim',
      descricaoTentativa: 'Contato anterior com SAC sem devolutiva tecnica suficiente.',
      situacaoEmAndamento: 'sim',
      riscoImediato: 'nao',
      manifestante: {
        tipoIdentificacao: 'identificada',
        nome: 'Marina Soares',
        email: 'marina@email.com',
        relacaoArtGlass: 'cliente',
        desejaRetorno: 'email',
        consentimentoLgpd: true,
        declaracaoVerdade: true,
      },
      areaResponsavelId: 'dept-producao',
      responsavelAtualId: 'user-maria-area',
      prazoRespostaInicial: isoDaysFromNow(2),
      prazoRespostaFinal: isoDaysFromNow(6),
      dataRespostaInicial: isoDaysFromNow(-1),
      prorrogada: true,
      justificativaProrrogacao: 'A area tecnica solicitou prazo adicional para validar informacoes de campo.',
      anexos: [],
      comunicacoes: [
        {
          id: 'com-5',
          tipo: 'intermediaria',
          assunto: `Atualizacao de prazo - ${gerarProtocolo(5)}`,
          corpo: 'A tratativa foi prorrogada de forma justificada para conclusao da analise tecnica.',
          de: 'Ouvidoria ArtGlass',
          para: 'marina@email.com',
          status: 'enviada',
          canal: 'email',
          enviadaEm: isoDaysFromNow(-1),
          criadaEm: isoDaysFromNow(-1),
        },
      ],
      comentarios: [],
      timeline: [
        {
          id: 'time-9',
          data: isoDaysFromNow(-3),
          usuario: 'Sistema',
          acao: 'Manifestacao registrada',
          descricao: 'Solicitacao complexa recebida com protocolo para acompanhamento.',
          visibilidade: 'publica',
        },
        {
          id: 'time-10',
          data: isoDaysFromNow(-1),
          usuario: 'Maria Silva',
          acao: 'Prorrogacao comunicada',
          descricao: 'Manifestante informado sobre nova previsao de retorno.',
          visibilidade: 'publica',
        },
      ],
      criadoEm: isoDaysFromNow(-3),
      atualizadoEm: isoDaysFromNow(-1),
    },
    {
      id: 'man-6',
      protocolo: gerarProtocolo(6),
      natureza: 'consulta',
      naturezaOriginal: 'consulta',
      assunto: 'processo_interno',
      complexidade: 'baixa',
      prioridade: 'baixa',
      status: 'arquivada',
      statusPublico: 'arquivada',
      laneAtual: 'ouvidoria',
      canalOrigem: 'site',
      titulo: 'Consulta sem aderencia ao escopo da Ouvidoria',
      descricao: 'Consulta relacionada a assunto externo sem vinculacao direta com a ArtGlass.',
      tentativaAnterior: 'nao_aplica',
      situacaoEmAndamento: 'nao',
      riscoImediato: 'nao',
      manifestante: {
        tipoIdentificacao: 'identificada',
        nome: 'Marcos Vieira',
        email: 'marcos@email.com',
        relacaoArtGlass: 'comunidade',
        desejaRetorno: 'email',
        consentimentoLgpd: true,
        declaracaoVerdade: true,
      },
      responsavelAtualId: 'user-ana-ouvidoria',
      prazoRespostaInicial: isoDaysFromNow(-7),
      prazoRespostaFinal: isoDaysFromNow(-4),
      dataRespostaInicial: isoDaysFromNow(-7),
      dataRespostaFinal: isoDaysFromNow(-6),
      prorrogada: false,
      anexos: [],
      comunicacoes: [],
      comentarios: [],
      timeline: [
        {
          id: 'time-11',
          data: isoDaysFromNow(-8),
          usuario: 'Sistema',
          acao: 'Manifestacao registrada',
          descricao: 'Consulta recebida pela Ouvidoria.',
          visibilidade: 'publica',
        },
      ],
      criadoEm: isoDaysFromNow(-8),
      atualizadoEm: isoDaysFromNow(-6),
      concluidoEm: isoDaysFromNow(-6),
      arquivadoEm: isoDaysFromNow(-6),
    },
    {
      id: 'man-7',
      protocolo: gerarProtocolo(7),
      natureza: 'denuncia',
      naturezaOriginal: 'denuncia',
      assunto: 'fraude',
      complexidade: 'alta',
      prioridade: 'critica',
      status: 'em_investigacao',
      statusPublico: 'em_apuracao',
      laneAtual: 'comite_etica',
      canalOrigem: 'site',
      titulo: 'Suspeita de fraude em processo de compras',
      descricao: 'Relato sobre possivel fraude em aprovacao de pedidos de compras.',
      tentativaAnterior: 'nao',
      situacaoEmAndamento: 'nao_sei',
      riscoImediato: 'sim',
      manifestante: {
        tipoIdentificacao: 'anonima',
        desejaRetorno: 'anonimo',
        consentimentoLgpd: true,
        declaracaoVerdade: true,
      },
      responsavelAtualId: 'user-paula-comite',
      prazoRespostaInicial: isoDaysFromNow(-1),
      prazoRespostaFinal: isoDaysFromNow(12),
      dataRespostaInicial: isoDaysFromNow(-6),
      prorrogada: false,
      anexos: [],
      comunicacoes: [],
      comentarios: [],
      timeline: [
        {
          id: 'time-12',
          data: isoDaysFromNow(-6),
          usuario: 'Sistema',
          acao: 'Denuncia registrada',
          descricao: 'Denuncia anonima recebida para triagem.',
          visibilidade: 'publica',
        },
      ],
      criadoEm: isoDaysFromNow(-6),
      atualizadoEm: isoDaysFromNow(-2),
    },
  ]
}

function buildSurveys(): SatisfactionSurveyRecord[] {
  return [
    {
      id: 'survey-1',
      manifestacaoId: 'man-3',
      notaGeral: 5,
      clareza: 5,
      tempoResposta: 4,
      respeito: 5,
      demandaCompreendida: 'sim',
      desejaReabrir: false,
      comentario: 'Atendimento claro e retorno dentro do esperado.',
      criadoEm: isoDaysFromNow(-4),
    },
    {
      id: 'survey-2',
      manifestacaoId: 'man-4',
      notaGeral: 4,
      clareza: 4,
      tempoResposta: 4,
      respeito: 5,
      demandaCompreendida: 'sim',
      desejaReabrir: false,
      comentario: 'Fluxo simples e objetivo.',
      criadoEm: isoDaysFromNow(-1),
    },
    {
      id: 'survey-3',
      manifestacaoId: 'man-6',
      notaGeral: 3,
      clareza: 3,
      tempoResposta: 4,
      respeito: 4,
      demandaCompreendida: 'parcialmente',
      desejaReabrir: false,
      criadoEm: isoDaysFromNow(-5),
    },
  ]
}

export function createSeedDatabase(): AppDatabase {
  const now = new Date().toISOString()

  return {
    versao: 1,
    sequencialProtocolo: 7,
    settings: buildSettings(),
    departamentos: buildDepartments(now),
    usuarios: buildUsers(now),
    templates: buildTemplates(now),
    manifestacoes: buildManifestations(now),
    pesquisas: buildSurveys(),
    sessoes: [],
  }
}
